
use schema FSI_DEMOS.WEALTH;

create or replace TABLE FSI_DEMOS.WEALTH.CUSTOMERS (
	CID NUMBER(38,0),
	FIRST_NAME VARCHAR,
	LAST_NAME VARCHAR,
	CUST_TYPE VARCHAR,
	OCCUPATION VARCHAR,
	DOMICILE VARCHAR,
	DOB DATE,
	MARITAL_STATUS VARCHAR,
	DEPENDENTS VARCHAR,
	CUSTOMER_DATE DATE,
	SHORT_TERM_GOALS VARCHAR,
	LONG_TERM_GOALS VARCHAR,
	ANNUAL_INCOME VARCHAR,
	MONTHLY_EXPENSES VARCHAR,
	EXISTING_DEBTS VARCHAR,
	INTEREST_RATES VARCHAR,
	REPAYMENT_TERMS VARCHAR,
	MONTHLY_SAVINGS_INVESTMENTS VARCHAR,
	RISK_TOLERANCE VARCHAR,
	PAST_INVESTMENT_EXPERIENCE VARCHAR,
	INVESTMENT_INTERESTS VARCHAR,
	ETHICAL_INVESTING_INTEREST VARCHAR,
	PLANNED_RETIREMENT_AGE NUMBER(38,0),
	RETIREMENT_LIFESTYLE VARCHAR,
	INSURANCE_TYPES VARCHAR,
	WILL_TRUST VARCHAR,
	LEGACY_GOALS VARCHAR,
	TAX_ADVISOR_ENGAGEMENT VARCHAR
);

create or replace TABLE FSI_DEMOS.WEALTH.PORTFOLIO_DATA (
	CID NUMBER(38,0),
	TYPE VARCHAR,
	ASSET_CLASS VARCHAR,
	INSTRUMENT VARCHAR,
	DENOMINATION VARCHAR,
	AMOUNT NUMBER(38,2),
	YTD_RETURN NUMBER(38,2),
	"1Y_Return" NUMBER(38,2),
	"3Y_Return" NUMBER(38,2),
	"5Y_Return" NUMBER(38,2)
);

create or replace TABLE FSI_DEMOS.WEALTH.RELATIONSHIP_HISTORY (
	CID NUMBER(38,0),
	INTERACTION_DATE DATE,
	INTERACTION_TYPE VARCHAR,
	KEY_POINTS_DISCUSSED VARCHAR,
	CUSTOMER_SATISFACTION_SCORE NUMBER(38,0),
	YEARS_AS_CUSTOMER NUMBER(38,0),
	CHURN_RISK_SCORE NUMBER(38,0),
	PAST_MEETING_NOTES VARCHAR,
	RECOMMENDED_PRODUCTS VARCHAR
);

create or replace TABLE FSI_DEMOS.WEALTH.SUPPORT_CASES (
	CASE_ID VARCHAR,
	CATEGORY VARCHAR,
	TRANSCRIPT VARCHAR
);

-- LOAD DATA, NOTE THAT THE FILES HAVE HEADER FOR FIRST ROW AND THE COLUMNS HAVE ;  AS THE SEPERATOR

CREATE OR REPLACE WAREHOUSE CORTEX_WEALTH_SEARCH_WH
 WAREHOUSE_SIZE = SMALL;

CREATE CORTEX SEARCH SERVICE  FSI_DEMOS.WEALTH.WEALTH_MEETING_SEARCH
ON PAST_MEETING_NOTES
ATTRIBUTES CID, INTERACTION_TYPE
WAREHOUSE = CORTEX_WEALTH_SEARCH_WH
TARGET_LAG = '1 minutes'
AS
(SELECT
		CID, INTERACTION_DATE, INTERACTION_TYPE, PAST_MEETING_NOTES
	FROM FSI_DEMOS.WEALTH.RELATIONSHIP_HISTORY
);
-- This service is currently not used
/*
CREATE OR REPLACE CORTEX SEARCH SERVICE  FSI_DEMOS.WEALTH.WEALTH_SUPPORT_SEARCH
ON TRANSCRIPT
ATTRIBUTES CASE_ID, CATEGORY
WAREHOUSE = CORTEX_WEALTH_SEARCH_WH
TARGET_LAG = '1 minutes'
AS
(
    select CASE_ID, CATEGORY, CASE_ID || ': ' || TRANSCRIPT AS TRANSCRIPT from  FSI_DEMOS.WEALTH.SUPPORT_CASES
);
*/

-- Current version of the Demo is not using Cortex Analys so this is optional
CREATE OR REPLACE STAGE FSI_DEMOS.WEALTH.YAML_STAGE;
-- UPLOAD wealth_semantic_layer.yaml to YAML_STAGE

-- Create a new Streamlit application and paste the content of streamlit_app.py, add snowflake-snowpark-python and snowflake.core

-- Questions for the Chat part are in the README
