use schema FSI_DEMOS.WEALTH;

create or replace TABLE FSI_DEMOS.WEALTH.CUSTOMERS (
	CID NUMBER(38,0),
	FIRST_NAME VARCHAR,
	LAST_NAME VARCHAR,
	CUST_TYPE VARCHAR,
	OCCUPATION VARCHAR,
	DOMICILE VARCHAR,
	DOB DATE,
	MARITAL_STATUS VARCHAR,
	DEPENDENTS VARCHAR,
	CUSTOMER_DATE DATE,
	SHORT_TERM_GOALS VARCHAR,
	LONG_TERM_GOALS VARCHAR,
	ANNUAL_INCOME VARCHAR,
	MONTHLY_EXPENSES VARCHAR,
	EXISTING_DEBTS VARCHAR,
	INTEREST_RATES VARCHAR,
	REPAYMENT_TERMS VARCHAR,
	MONTHLY_SAVINGS_INVESTMENTS VARCHAR,
	RISK_TOLERANCE VARCHAR,
	PAST_INVESTMENT_EXPERIENCE VARCHAR,
	INVESTMENT_INTERESTS VARCHAR,
	ETHICAL_INVESTING_INTEREST VARCHAR,
	PLANNED_RETIREMENT_AGE NUMBER(38,0),
	RETIREMENT_LIFESTYLE VARCHAR,
	INSURANCE_TYPES VARCHAR,
	WILL_TRUST VARCHAR,
	LEGACY_GOALS VARCHAR,
	TAX_ADVISOR_ENGAGEMENT VARCHAR
);

create or replace TABLE FSI_DEMOS.WEALTH.PORTFOLIO_DATA (
	CID NUMBER(38,0),
	TYPE VARCHAR,
	ASSET_CLASS VARCHAR,
	INSTRUMENT VARCHAR,
	DENOMINATION VARCHAR,
	AMOUNT NUMBER(38,2),
	YTD_RETURN NUMBER(38,2),
	"1Y_Return" NUMBER(38,2),
	"3Y_Return" NUMBER(38,2),
	"5Y_Return" NUMBER(38,2)
);

create or replace TABLE FSI_DEMOS.WEALTH.RELATIONSHIP_HISTORY (
	CID NUMBER(38,0),
	INTERACTION_DATE DATE,
	INTERACTION_TYPE VARCHAR,
	KEY_POINTS_DISCUSSED VARCHAR,
	CUSTOMER_SATISFACTION_SCORE NUMBER(38,0),
	YEARS_AS_CUSTOMER NUMBER(38,0),
	CHURN_RISK_SCORE NUMBER(38,0),
	PAST_MEETING_NOTES VARCHAR,
	RECOMMENDED_PRODUCTS VARCHAR
);

create or replace TABLE FSI_DEMOS.WEALTH.SUPPORT_CASES (
	CASE_ID VARCHAR,
	CATEGORY VARCHAR,
	TRANSCRIPT VARCHAR
);

-- LOAD DATA, NOTE THAT THE FILES HAVE HEADER FOR FIRST ROW AND THE COLUMNS HAVE ;  AS THE SEPERATOR

---- Staging area for the CSV files

create or replace stage CSV ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') DIRECTORY = ( ENABLE = true );

-- Copy the docs for bikes
COPY FILES
    INTO @CSV/
    FROM @FSI_DEMOS.WEALTH.git_repo/branches/main/data/;

ALTER STAGE CSV REFRESH;

ls @CSV;

copy into customers
    from @CSV
    FILES = ('CUSTOMERS.csv')
    FILE_FORMAT = (TYPE = 'CSV', FIELD_DELIMITER = ';', SKIP_HEADER = 1);


copy into PORTFOLIO_DATA
    from @CSV
    FILES = ('PORTFOLIO_DATA.csv')
    FILE_FORMAT = (TYPE = 'CSV', FIELD_DELIMITER = ';', SKIP_HEADER = 1);


copy into RELATIONSHIP_HISTORY
    from @CSV
    FILES = ('RELATIONSHIP_HISTORY.csv')
    FILE_FORMAT = (TYPE = 'CSV', FIELD_DELIMITER = ';', SKIP_HEADER = 1);


copy into SUPPORT_CASES
    from @CSV
    FILES = ('SUPPORT_CASES.csv')
    FILE_FORMAT = (TYPE = 'CSV', FIELD_DELIMITER = ';', SKIP_HEADER = 1)
    ON_ERROR = CONTINUE;

--- Cortex Search Service for the Chatbot for meeting notes

CREATE OR REPLACE WAREHOUSE CORTEX_WEALTH_SEARCH_WH
 WAREHOUSE_SIZE = SMALL;

CREATE CORTEX SEARCH SERVICE  WEALTH_MEETING_SEARCH
ON PAST_MEETING_NOTES
ATTRIBUTES CID, INTERACTION_TYPE
WAREHOUSE = CORTEX_WEALTH_SEARCH_WH
TARGET_LAG = '1 hour'
AS
(SELECT
		CID, INTERACTION_DATE, INTERACTION_TYPE, PAST_MEETING_NOTES
	FROM RELATIONSHIP_HISTORY
);

--- Copy Semantic File to be used by Cortex Analyst:

CREATE OR REPLACE STAGE YAML_STAGE ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') DIRECTORY = ( ENABLE = true );

COPY FILES
    INTO @YAML_STAGE/
    FROM @FSI_DEMOS.WEALTH.git_repo/branches/main/
    FILES = ('wealth_semantic_layer.yaml');

--- Install Streamlit App:
    
CREATE OR REPLACE STREAMLIT WEALTH_360_APP
        FROM @FSI_DEMOS.WEALTH.git_repo/branches/main/app
        MAIN_FILE = 'streamlit_app.py'
        QUERY_WAREHOUSE = 'COMPUTE_WH'
        TITLE = 'Wealth 360 App'
        COMMENT = 'Demo for Wealth 360';

